### ISSUE TITLE
BeerJS #1: 12 апреля 2018

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#1]
Дата: 12 апреля 2018, 19:00
Место: [«Коза»](http://koza74.ru) (Труда, 156)

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs1.ics)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍺

**Comment by IH8E** [comment]
:beers:

**Comment by VadimZvf** [comment]
🍺

**Comment by edele** [comment]
🎉 🐫 🎈

**Comment by xostik** [comment]
✔

**Comment by rodionovstepan** [comment]
🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺🍺

**Comment by Servik17** [comment]
+

**Comment by razio** [comment]
🍺

**Comment by korenb** [comment]
🐘

**Comment by Alorian** [comment]
+

**Comment by Servik17** [comment]
Доклад о typescript и flow
https://youtu.be/etKOc80-cw0

**Comment by igor-shevchenko** [comment]
Спасибо всем, кто пришел! Отлично посидели и пообщались. Некоторые темы, которые мы обсудили:
* Игровые движки: [Phaser](https://phaser.io) и [Pixi](http://www.pixijs.com).
* Фронтендовые фреймворки (React, Angular, Vue) и бэкендовые фреймворки (Express, Koa и более свежий [nest](https://nestjs.com/)).
* Реактивность в ангуляре. [Observables](https://angular.io/guide/observables) и [сравнение их с промизами](https://angular.io/guide/comparing-observables). Библиотеки [RxJS](http://reactivex.io/rxjs/) и Редакс для ангуляра [ngrx/store](https://github.com/ngrx/platform/blob/master/docs/store/README.md).
* Разработка десктопных приложений на [электроне](https://electronjs.org).
* [TypeScript](http://www.typescriptlang.org/) и [Flow](https://flow.org) — в чем разница между ними и [почему во Flow более строгая система типов](https://www.youtube.com/watch?v=etKOc80-cw0&feature=youtu.be).
* Базы данных — PostgreSQL, MySQL, MSSQL, MongoDB, [CouchDB](http://couchdb.apache.org/) и [PouchDB](https://pouchdb.com/). Доклады Евгения Климова о базах данных на [Python-митапе](https://www.youtube.com/watch?v=_je9o0Y03rs) и [Java-встрече](https://www.youtube.com/watch?v=vylfWQeL1Nk).
* [CRDT](https://twitter.com/sitnikcode/status/983781952292577280) и [Logux](https://twitter.com/sitnikcode/status/984199428214009859), как гугл-доки разрешают конфликты.
* [Вебсокеты](https://ru.wikipedia.org/wiki/WebSocket), сколько соединений выдерживают сервера и почему бэкендеры предпочитают вебсокетам лонг-поллинг. Как Hangouts справляется с большой нагрузкой при передаче видео.
* Как начать писать модульные тесты. На следующей встрече @edele обещал рассказать об этом подробнее.
* Может ли фронтенд быть микросервисным и как убедить бизнес, что нам нужны микросервисы, логи и докер.
* Сколько часов в день должен работать программист.
* Продуктовая разработка — как смотреть на метрики при добавлении фич, и почему иногда из этого получаются очень плохие продукты.
* Внедрение скрама. [Настоящий скрам](https://www.scrumguides.org/docs/scrumguide/v2017/2017-Scrum-Guide-Russian.pdf) и скрамбат.
* Что лучше — переписывать проекты с нуля или переделывать их понемногу, поддерживая две версии сразу. Поделились страшными историями.
* Другие мероприятия о фронтенде в Челябинске. Через неделю будет митап [Frontday](https://meetup.house/frontday/), а через месяц — конференция [UWDC](http://uwdc.ru) с секцией фронтенда.

![photo5368835645897812273](https://user-images.githubusercontent.com/1195931/38767443-9865cff4-3ffa-11e8-80cf-b0eb6fd5f4ae.jpg)

До следующих встреч! 🍺

**Comment by Globik** [comment]
Ну дык, уже давно прошло всё. Мммжаль...
