### ISSUE TITLE
BeerJS #12: 16 Сентября 2021

### ISSUE THREAD

**Issue by alorian** [beerjs/chelyabinsk#12]
Дата: 16 Сентября 2021, 19:00

Место: Бар "5561 пересечение вкусов", ​ул. Труда, 67​
https://5561-bar.ru
https://2gis.ru/chelyabinsk/firm/70000001039497591?m=61.414154%2C55.167675%2F18

[Добавить в календарь через файл ics](https://verstaem.com/events/beerjs12.ics)

[Добавить в гугл календарь](https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=MTJtc2RkbXJ1ZXU3bDUydm5lZzZ0aHZhNjMgYWxlcm1pb25AbQ&amp;tmsrc=alermion%40gmail.com)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍻

**Comment by KlimMalgin** [comment]
👍

**Comment by IH8E** [comment]
🍻

**Comment by Nosterx** [comment]
+

**Comment by razio** [comment]
🍺

**Comment by mcferden** [comment]
🍸

**Comment by welerone** [comment]
🍻

**Comment by loktevra** [comment]
+

**Comment by tsvetkovda** [comment]
🥃

**Comment by alorian** [comment]
Спасибо всем пришедшим :)

![photo_2021-09-20_01-44-35](https://user-images.githubusercontent.com/572222/133942540-99919d8c-39e8-44d5-94e0-dd7547bbcd82.jpg)
![photo_2021-09-20_01-44-48](https://user-images.githubusercontent.com/572222/133942539-1fe928d0-fec8-482e-8d1b-f2a447d62f87.jpg)

**Comment by igor-shevchenko** [comment]
@alorian спасибо, что организовал встречу!
