### ISSUE TITLE
BeerJS #16: 15 февраля 2024

### ISSUE THREAD

**Issue by alorian** [beerjs/chelyabinsk#16]
Дата 15 февраля 2024
Время 20:00

Место "Hottabych" Улица Цвиллинга, 15/1
https://go.2gis.com/3yoy8
https://yandex.ru/maps/-/CDB7Q6Ke

В программе доклад о том как писать IaaC (инфраструктура как код) на JS. И о том как инфраструктурный код можно объединять с бизнес логикой.

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий

**Comment by IH8E** [comment]
![image](https://github.com/beerjs/chelyabinsk/assets/6886122/a089cb0e-a086-4332-8494-53cfd9f468c3)

**Comment by Valvishe** [comment]
3 SQL databases walked into a NoSQL bar. A little while later they walked out, because they couldn’t find a table.

**Comment by mrtheyann** [comment]
![image](https://github.com/beerjs/chelyabinsk/assets/15281217/486d8f06-6217-4f84-b672-f39c5c7ffe2b)

**Comment by P9os** [comment]
+

**Comment by olgakiba18796** [comment]
любой комментарий

**Comment by voznin** [comment]
+1

**Comment by evgeniy-logvinov** [comment]
+1

**Comment by razdolbaipozhizni** [comment]
уникальный комментарий)

**Comment by HoustonKek** [comment]
0_0

**Comment by Split174** [comment]
any comment

**Comment by tsvetkovda** [comment]
ight

**Comment by TiMirLAN** [comment]
`.*`

**Comment by bigslycat** [comment]
пиу

**Comment by shvartem** [comment]
+

**Comment by welerone** [comment]
![image](https://github.com/beerjs/chelyabinsk/assets/27738717/2b41fc84-f251-44ed-ae97-daebd199bce3)

**Comment by alorian** [comment]
![IMG_5832](https://github.com/beerjs/chelyabinsk/assets/572222/381941ca-cdb9-4939-8714-dbf91bb79d7a)
![photo_2024-02-16_14-19-43](https://github.com/beerjs/chelyabinsk/assets/572222/43a7df7c-8adc-449d-a3af-a4588fdc8099)
![IMG_5831](https://github.com/beerjs/chelyabinsk/assets/572222/ecd3f22d-2050-478e-a356-06cea36c3241)
![IMG_5830](https://github.com/beerjs/chelyabinsk/assets/572222/4c341db4-5fe4-4b7c-a686-68ed2aa586fa)
![IMG_5829](https://github.com/beerjs/chelyabinsk/assets/572222/83d4467c-bc33-4849-a580-5c4a6b191bb8)
