### ISSUE TITLE
BeerJS #2: 9 августа 2018

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#2]
Дата: 9 августа 2018, 19:30
Место: [«Hoppy Mondays»](https://vk.com/hoppymondays) (Кирова, 82д)

@edele расскажет о том, как начать писать юнит-тесты для фронтенда

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs2.ics)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🐈

**Comment by razonrus** [comment]
🤶

**Comment by razio** [comment]
🔥

**Comment by ekozelkova** [comment]
🦆

**Comment by ksetrin** [comment]
any comment

**Comment by Alorian** [comment]
+

**Comment by bububo** [comment]
✌

**Comment by danilDelete** [comment]
Планирую пойти.

**Comment by loktevra** [comment]
:+1:

**Comment by archisf** [comment]
✌️

**Comment by x-raizor** [comment]
:D

**Comment by vetalin** [comment]
+

**Comment by IH8E** [comment]
:beers:

**Comment by MAaxim91** [comment]
🧙‍♂️

**Comment by DBalashov** [comment]
Буду

**Comment by Anton9408** [comment]
Буду

**Comment by dipiash** [comment]
+

**Comment by edele** [comment]
:wave:

**Comment by PingLa1** [comment]
-

**Comment by Jankelbrod** [comment]
Приду

**Comment by AlsGrm** [comment]
👀

**Comment by samitsme74** [comment]
"Любой комментарий".

**Comment by razonrus** [comment]
К сожалению, не смогу быть

**Comment by igor-shevchenko** [comment]
Спасибо всем, кто пришел, и отдельное спасибо @edele за отличный доклад! Материалы доклада Идель обещает скоро выложить, пока что можно посмотреть видео про [10 глупых вопросов хирургу](https://youtu.be/xjGO2RaDpI4).

Анонсы встреч публикуются здесь в виде ишью. Ставьте 👁️ этому репозиторию, чтобы получить уведомления о них, и добавляйтесь в [телеграм-чат](https://t.me/beerjs_chel), где мы общаемся.

Если вы хотите о чем-то рассказать в формате BeerJS — предлагайте. Это может быть любой доклад — большой или маленький, про технологии или про жизнь, конструктивный или провокационный :)  

Не забывайте, что в Челябинске есть и другие мероприятия про фронтенд: в эту пятницу (17 августа) будет митап [Frontday](https://meetup.house/frontday/).

Еще раз спасибо всем. До следующих встреч! 🍻 

![](https://user-images.githubusercontent.com/1195931/44069923-9c5cae98-9f9a-11e8-98a2-a5ac0c4911fb.jpg)

![](https://user-images.githubusercontent.com/1195931/44069936-ab0e41a4-9f9a-11e8-8cb0-85f1b00d2b62.jpg)

**Comment by igor-shevchenko** [comment]
А вот и материалы доклада про тесты: https://github.com/edele/beerjs

**Comment by Globik** [comment]
Хм, опоздал.

**Comment by igor-shevchenko** [comment]
Третий BeerJS будет 17 января, подключайтесь: https://github.com/beerjs/chelyabinsk/issues/3
