### ISSUE TITLE
BeerJS #3: 17 января 2019

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#3]
Дата: 17 января 2019, 19:30
Место: [«Brothers»](https://vk.com/brothers74) (Кирова, 110)

@Amareis расскажет про образование и проведет тематический [«Конверсейшн»](https://habr.com/company/mosigra/blog/433968/)

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs3.ics)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍺

**Comment by Amareis** [comment]
🍺🍺🍺

**Comment by edele** [comment]
🍺🍺🍺🍺🍺🍺🍺🍺🍺

**Comment by IH8E** [comment]
:beers:

**Comment by Alorian** [comment]
+

**Comment by xostik** [comment]
⚓

**Comment by Globik** [comment]
Непонятно, шо за коверсейшн такое. Игра?

**Comment by igor-shevchenko** [comment]
@Globik да, вот здесь подробнее описано: https://habr.com/company/mosigra/blog/433968/

**Comment by digitalduke** [comment]
+1

**Comment by Globik** [comment]
Можно и reactjs в conversation-формате обсудить. Почему он тяжел и вовсе не реактивен. Самые тяжелые юзкейсы, как в https://vk.com/club173284959

**Comment by kolmakovruslan** [comment]
🍺

**Comment by Megachel** [comment]
+

**Comment by mistakster** [comment]
🍺

**Comment by Lara0Yu** [comment]
+1

**Comment by igor-shevchenko** [comment]
И снова спасибо всем, кто пришел! Был очень рад со всеми познакомиться и пообщаться.

Доклад @Amareis 
про образование программиста можно перечитать в виде текста, он доступен здесь: https://vk.com/@from_metal-thoughts

До новых встреч 🍻 

![2019-01-17 21-44-30](https://user-images.githubusercontent.com/1195931/51409125-bd787f80-1b82-11e9-9bd9-bce4fefd18de.JPG)
