### ISSUE TITLE
BeerJS #4: 18 апреля 2019

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#4]
Дата: 18 апреля 2019, 19:30
Место: [«Jackson's bar&grill»](http://www.jacksons74.ru) (Свердловский проспект, 64Д)

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs4.ics)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍻

**Comment by kolmakovruslan** [comment]
🍺

**Comment by digitalduke** [comment]
+1

**Comment by cryszero** [comment]
+

**Comment by militska** [comment]
+

**Comment by edele** [comment]
🦄

**Comment by Amareis** [comment]
++

**Comment by Servik17** [comment]
🍺

**Comment by gulyash** [comment]
Ы

**Comment by Weiaett** [comment]
+1

**Comment by panchenkoas** [comment]
😏

**Comment by loktevra** [comment]
+1

**Comment by mcferden** [comment]
±1

**Comment by IH8E** [comment]
:beers:

**Comment by vendeva** [comment]
+

**Comment by alexeygasenko** [comment]
±1

**Comment by igor-shevchenko** [comment]
🍺 

![photo_2019-04-19_23-12-31](https://user-images.githubusercontent.com/1195931/56437753-0ebb1b00-62fa-11e9-95dc-cbccc8df4bf8.jpg)

**Comment by Globik** [comment]
Я не приду, к сожалению.
