### ISSUE TITLE
BeerJS #5: 4 сентября 2019

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#5]
Дата: 4 сентября 2019, 19:30
Место: [«Jackson's bar&grill»](http://www.jacksons74.ru) (Свердловский проспект, 64Д)

@edele расскажет об истории развития компьютерных платформ: поностальгируем по платформам прошлого и обсудим платформы, с которыми работаем сегодня.

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs5.ics)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍻

**Comment by digitalduke** [comment]
+1

**Comment by IH8E** [comment]
🍺

**Comment by Globik** [comment]
+1

**Comment by alorian** [comment]
+1

**Comment by Servik17** [comment]
+1

**Comment by razio** [comment]
🔫

**Comment by Globik** [comment]
@razio, о, нет!

**Comment by edele** [comment]
🐝

**Comment by ping2lai2** [comment]
-

**Comment by panchenkoas** [comment]
🥳

**Comment by gulyash** [comment]
🐌

**Comment by mcferden** [comment]
:thinking:

**Comment by Dozer74** [comment]
+

**Comment by Globik** [comment]
Не приду. Настроения нет. Работу не могу найти.

**Comment by Globik** [comment]
Ну а что? Я ж не знаю, сколько пиво в баре стоит. Там все такие успешные, а я не из вашего круга.

**Comment by igor-shevchenko** [comment]
Спасибо всем, кто вчера пришел! Вот пара фоток, простите за качество :)
![2019-09-04 20-17-27](https://user-images.githubusercontent.com/1195931/64344543-190b5680-d008-11e9-99ea-d3bcb4dc816a.JPG)
![2019-09-04 20-41-45](https://user-images.githubusercontent.com/1195931/64344544-190b5680-d008-11e9-9f10-2cff6781c09e.JPG)

**Comment by igor-shevchenko** [comment]
> Ну а что? Я ж не знаю, сколько пиво в баре стоит. Там все такие успешные, а я не из вашего круга.

Пиво было от 100 рублей. Всех приветствуем :)
