### ISSUE TITLE
BeerJS #7: 2 апреля 2020 года

### ISSUE THREAD

**Issue by igor-shevchenko** [beerjs/chelyabinsk#7]
Дата: 2 апреля 2020, 19:30
Место: [Zoom](https://zoom.us/)

[Добавить в календарь](http://igorshevchenko.ru/download/beerjs7.ics)

Встречаемся онлайн в карантинном формате. Ссылка на созвон будет [в чате](https://t.me/beerjs_chel) в четверг. 

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍺

**Comment by Sollen** [comment]
😈🔥

**Comment by mcferden** [comment]
🍺

**Comment by IH8E** [comment]
:beers:

**Comment by ping2lai2** [comment]
![](https://github.githubassets.com/images/icons/emoji/unicode/1f37a.png)

**Comment by edele** [comment]
🇰🇿

**Comment by Servik17** [comment]
🍺

**Comment by mrtheyann** [comment]
🍻

**Comment by Ingwar121** [comment]
🍷

**Comment by Weiaett** [comment]
🇷🇺🍻🇳🇱

**Comment by igor-shevchenko** [comment]
Спасибо всем, кто пришел 🍺 
![image](https://user-images.githubusercontent.com/1195931/78534594-17a34600-7804-11ea-9855-6e89abfe006e.png)
