### ISSUE TITLE
BeerJS #8: 5 сентября 2020

### ISSUE THREAD

**Issue by alorian** [beerjs/chelyabinsk#8]
Дата: 5 сентября 2020, Суббота, 19:30
Место зависит от количества участников. 

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by alorian** [comment]
+

**Comment by freedomrezo** [comment]
🦕

**Comment by alorian** [comment]
Так как мало кто готов собраться - без брони. Место [Винный шкаф](https://vk.com/vinniyshkaf) на пешеходной кировке.

Координация в телеграм чате
https://t.me/beerjs_chel

**Comment by edele** [comment]
🍷

**Comment by alorian** [comment]
Первая встреча после карантина состоялась :)
Забыл сфотографировать для истории. 

Спасибо пришедшим :)
