### ISSUE TITLE
BeerJS #9: 11 февраля 2021

### ISSUE THREAD

**Issue by IH8E** [beerjs/chelyabinsk#9]
Дата: 11 февраля 2021, 19:00
Место: [«Jackson's bar&grill»](http://www.jacksons74.ru) (Свердловский проспект, 64Д)

Если вы придете, сообщите нам об этом, оставив здесь любой комментарий.

**Comment by igor-shevchenko** [comment]
🍺🍺🍺🍺🍺

**Comment by mrtheyann** [comment]
🍻

**Comment by altpoint** [comment]
А в шаббат то шо таки никак?

**Comment by KlimMalgin** [comment]
🍺 🐝

**Comment by igor-shevchenko** [comment]
> А в шаббат то шо таки никак?

BeerJS стандартно проводится по четвергам, потому что в пятницу-субботу у многих запланированы свои тусовки, семейные дела, поездки на дачу и т. д. И в заведениях сложнее бронировать места на эти дни недели.

**Comment by Sollen** [comment]
I'm on it!)

**Comment by alorian** [comment]
+

**Comment by razio** [comment]
🍺

**Comment by Nosterx** [comment]
+

**Comment by yaz47** [comment]
🍺

**Comment by slavabezborodov56** [comment]
🍺

**Comment by Ingwar121** [comment]
🐍 🍺

**Comment by mcferden** [comment]
🐍 🍺

**Comment by vendeva** [comment]
+

**Comment by Globik** [comment]
Пиво с собой брать можно?

**Comment by igor-shevchenko** [comment]
> Пиво с собой брать можно?

Боюсь, что бар не разрешит.

**Comment by Globik** [comment]
Мля, а у меня ЗП только в пятницу

**Comment by tsvetkovda** [comment]
:goberserk:

**Comment by IH8E** [comment]
Спасибо всем, кто пришёл! 
![photo_2021-02-12_09-19-37](https://user-images.githubusercontent.com/6886122/107843549-17d58000-6ddd-11eb-89a5-85d14dec2074.jpg)
В следующий раз будет больше фото 👍
